package db

import (
	"fmt"
	"sort"

	"github.com/ArtemHvozdov/food-service-establishments/internal/domain"
)

func Places() []domain.CountryPlaceGroup {
	return []domain.CountryPlaceGroup{
		{
			Country: domain.Bulgaria,
			Cities: []domain.CityPlaceGroup{
				{
					City: domain.BulgariaVarna,
					Places: []domain.Place{
						{
							Alias:           "bg-varna-stefania-restaurant",
							PreviousAliases: nil,
							City:            domain.BulgariaVarna,
							Name:            "Stefania Restaurant",
							Address:         "бул. Княз Борис I 126, 9010 Варна, България",
							Type:            domain.Restaurant,
							URL:             "https://stefania.bg/bg/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/stefania_rest/?hl=bg/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/Restaurant+Stefania+DE/@52.5350217,13.6081279,17z/data=!3m1!4b1!4m6!3m5!1s0x47a84b00192cc3b5:0xc4b85b5d593e979a!8m2!3d52.5350217!4d13.6081279!16s%2Fg%2F11lmkc2wh9?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJb-6thO5VpEAR6upb0CSxOS4",
							Location: domain.Location{
								Latitude:  52.5350217,
								Longitude: 13.6081279,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.BulgariaSofia,
					Places: []domain.Place{
						{
							Alias:           "bg-sofia-faina-ukraina",
							PreviousAliases: nil,
							City:            domain.BulgariaSofia,
							Name:            "Файна Украина",
							Address:         "ул. Странджа 44, 1303 София, България",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/faina_ukraina_2026/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/%D0%A4%D0%B0%D0%B9%D0%BD%D0%B0+%D0%AE%D0%BA%D1%80%D0%B0%D0%B9%D0%BD%D0%B0/@42.6991315,23.3118459,17z/data=!3m1!4b1!4m6!3m5!1s0x40aa85bca639d98d:0x2a50d8f4492ee026!8m2!3d42.6991315!4d23.3118459!16s%2Fg%2F11z5641r8_?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJjdk5pryFqkARJuAuSfTYUCo",
							Location: domain.Location{
								Latitude:  42.6991315,
								Longitude: 23.3118459,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
						{
							Alias:           "bg-sofia-bistro-portokal",
							PreviousAliases: nil,
							City:            domain.BulgariaSofia,
							Name:            "Бистро Портокал",
							Address:         "кв. Банишора, ул. Опалченска 53, 1233 София, България",
							Type:            domain.Bistro,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/%D0%91%D0%B8%D1%81%D1%82%D1%80%D0%B8+,,%D0%9F%D0%BE%D1%80%D1%82%D0%BE%D0%BA%D0%B0%D0%BB%E2%80%9D/@42.7105402,23.3145189,17z/data=!4m16!1m9!3m8!1s0x40aa8555f0abbba5:0x8badbd7ce286cb9a!2z0JHQuNGB0YLRgNC4ICws0J_QvtGA0YLQvtC60LDQu-KAnQ!8m2!3d42.7105402!4d23.3145189!9m1!1b1!16s%2Fg%2F11sj5839rz!3m5!1s0x40aa8555f0abbba5:0x8badbd7ce286cb9a!8m2!3d42.7105402!4d23.3145189!16s%2Fg%2F11sj5839rz?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJpbur8FWFqkARmsuG4ny9rYs",
							Location: domain.Location{
								Latitude:  42.7105402,
								Longitude: 23.3145189,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
					},
				},
			},
		},
		{
			Country: domain.Cyprus,
			Cities: []domain.CityPlaceGroup{
				{
					City: domain.CyprusKouklia,
					Places: []domain.Place{
						{
							Alias:           "cy-kouklia-eda-family-cafe",
							PreviousAliases: nil,
							City:            domain.CyprusKouklia,
							Name:            "Eda Family Cafe",
							Address:         "Kouklia 8500, Cyprus",
							Type:            domain.Cafe,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/eda_family_cafe/",
							FacebookURL:     "https://www.facebook.com/people/EDA_family_cafe/100089954059264/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Eda+family+cafe/@34.7088816,32.5747878,17z/data=!3m1!4b1!4m6!3m5!1s0x14e71bc500341d0b:0x74caf78ede5ee4c9!8m2!3d34.7088816!4d32.5747878!16s%2Fg%2F11kjglygq_?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJCx00AMUb5xQRyeRe3o73ynQ",
							Location: domain.Location{
								Latitude:  34.7088816,
								Longitude: 32.5747878,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CyprusLarnaca,
					Places: []domain.Place{
						{
							Alias:           "cy-larnaca-berezka-store-cuisine",
							PreviousAliases: nil,
							City:            domain.CyprusLarnaca,
							Name:            "Berezka store & cuisine",
							Address:         "Lordou Vyrona 35, Larnaka 6023, Cyprus",
							Type:            domain.Cafe,
							URL:             "https://berezka.cy/en",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/berezka.cy/",
							FacebookURL:     "https://www.facebook.com/berezka.cy/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Berezka+store+%26+cuisine/@34.9162087,33.6349798,14z/data=!4m10!1m2!2m1!1sberezka+store+%26+cuisine+larnaca!3m6!1s0x14e083ef0d373bd9:0xb10c41f8a98927ac!8m2!3d34.9162087!4d33.6349798!15sCh9iZXJlemthIHN0b3JlICYgY3Vpc2luZSBsYXJuYWNhWiEiH2JlcmV6a2Egc3RvcmUgJiBjdWlzaW5lIGxhcm5hY2GSAQRkZWxpmgEjQ2haRFNVaE5NRzluUzBWSlEwRm5TVU5vZFZCdVVGaDNFQUXgAQD6AQUIhgEQKg!16s%2Fg%2F11k4q4rqt5?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ2Ts3De-D4BQRrCeJqfhBDLE",
							Location: domain.Location{
								Latitude:  34.9162087,
								Longitude: 33.6349798,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CyprusNicosia,
					Places: []domain.Place{
						{
							Alias:           "cy-nicosia-berezka-store-cuisine",
							PreviousAliases: nil,
							City:            domain.CyprusNicosia,
							Name:            "BEREZKA store & cuisine",
							Address:         "Platonos 1, Strovolos 2040, Nicosia, Cyprus",
							Type:            domain.Cafe,
							URL:             "https://berezka.cy/en",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/berezka.cy/",
							FacebookURL:     "https://www.facebook.com/berezka.cy/",
							GoogleMapsURL:   "https://www.google.com/maps/place/BEREZKA+store+%26+cuisine/@35.1388686,33.3418928,13z/data=!4m10!1m2!2m1!1sberezka+store+%26+cuisine+nicosia!3m6!1s0x14de1754cdfd4927:0x5de04cc2b998e1f8!8m2!3d35.1388686!4d33.3418928!15sCh9iZXJlemthIHN0b3JlICYgY3Vpc2luZSBuaWNvc2lhWiEiH2JlcmV6a2Egc3RvcmUgJiBjdWlzaW5lIG5pY29zaWGSAQ1tZWFsX3Rha2Vhd2F5mgEjQ2haRFNVaE5NRzluUzBWSlEwRm5TVVJFYlU5UU5XWm5FQUXgAQD6AQQIJhBA!16s%2Fg%2F11stfbb1tv?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJJ0n9zVQX3hQR-OGYucJM4F0",
							Location: domain.Location{
								Latitude:  35.1388686,
								Longitude: 33.3418928,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
					},
				},
			},
		},
		{
			Country: domain.Czechia,
			Cities: []domain.CityPlaceGroup{
				{
					City: domain.CzechiaBrno,
					Places: []domain.Place{
						{
							Alias:           "cz-brno-defiliada",
							PreviousAliases: nil,
							City:            domain.CzechiaBrno,
							Name:            "Defiliada",
							Address:         "Libušina tř. 2, 623 00 Brno-Kohoutovice, Česká republika",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "",
							FacebookURL:     "https://www.facebook.com/people/Defiliada-Defiliada/61577147900521/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Defiliada/@49.1954462,16.5400605,17z/data=!4m16!1m9!3m8!1s0x4712970053a25df9:0x9e9935778eda47cb!2sDefiliada!8m2!3d49.1954462!4d16.5400605!9m1!1b1!16s%2Fg%2F11xh3dg65b!3m5!1s0x4712970053a25df9:0x9e9935778eda47cb!8m2!3d49.1954462!4d16.5400605!16s%2Fg%2F11xh3dg65b?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ-V2iUwCXEkcRy0fajnc1mZ4",
							Location: domain.Location{
								Latitude:  49.1954462,
								Longitude: 16.5400605,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CzechiaJihlava,
					Places: []domain.Place{
						{
							Alias:           "cz-jihlava-u-cimbora",
							PreviousAliases: nil,
							City:            domain.CzechiaJihlava,
							Name:            "Přátelské Bistro U Cimbora",
							Address:         "Březinova 4690/144, 586 01 Jihlava, Česká republika",
							Type:            domain.Bistro,
							URL:             "https://ucimbora.cz/#",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "",
							FacebookURL:     "https://www.facebook.com/people/P%C5%99%C3%A1telsk%C3%A9-Bistro-U-Cimbora/100079996854694/",
							GoogleMapsURL:   "https://www.google.com/maps/place/P%C5%99%C3%A1telsk%C3%A9+Bistro+U+Cimbora/@49.4018175,15.6021138,17z/data=!3m1!4b1!4m6!3m5!1s0x470d1b007af02b3f:0x77347b5e75d098cf!8m2!3d49.4018175!4d15.6021138!16s%2Fg%2F11wwj46y3s?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJPyvwegAbDUcRz5jQdV57NHc",
							Location: domain.Location{
								Latitude:  49.4018175,
								Longitude: 15.6021138,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CzechiaKarlovyVary,
					Places: []domain.Place{
						{
							Alias:           "cz-karlovy-vary-ukraina-restaurace",
							PreviousAliases: nil,
							City:            domain.CzechiaKarlovyVary,
							Name:            "Ukrajna restaurace",
							Address:         "Západní 13, 360 01 Karlovy Vary, Česká republika",
							Type:            domain.Restaurant,
							URL:             "https://restauraceukrajina.cz/cs/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/Restaurace+%22Ukrajina%22+Karlovy+Vary,+%D0%A0%D0%B5%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BD+%22%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B0%22+%D0%9A%D0%B0%D1%80%D0%BB%D0%BE%D0%B2%D1%8B+%D0%92%D0%B0%D1%80%D1%8B,+Restaurant+%22Ukraine%22+in+Karlsbad+-+ukrajinsk%C3%A1+restaurace/@50.2294048,12.8638128,17z/data=!3m1!4b1!4m6!3m5!1s0x47a099f64c1ea48d:0xa6626c3b1506dcb8!8m2!3d50.2294048!4d12.8638128!16s%2Fg%2F11nn3nkz_8?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJjaQeTPaZoEcRuNwGFTtsYqY",
							Location: domain.Location{
								Latitude:  50.2294048,
								Longitude: 12.8638128,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CzechiaLiberec,
					Places: []domain.Place{
						{
							Alias:           "cz-liberec-po-nashomu",
							PreviousAliases: nil,
							City:            domain.CzechiaLiberec,
							Name:            "Po-Nashomu",
							Address:         "Vaňurova 458/13, 460 07 Liberec, Česká republika",
							Type:            domain.Restaurant,
							URL:             "https://po-nashomu.cz/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/po_nashomu_/",
							FacebookURL:     "https://www.facebook.com/CleopatraLiberec",
							GoogleMapsURL:   "https://www.google.com/maps/place/Po-Nashomu/@50.7642331,15.0472529,17z/data=!3m1!4b1!4m6!3m5!1s0x470937001ca79a9f:0x3d3a2ca51cb59122!8m2!3d50.7642331!4d15.0472529!16s%2Fg%2F11n4tcdf73?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJn5qnHAA3CUcRIpG1HKUsOj0",
							Location: domain.Location{
								Latitude:  50.7642331,
								Longitude: 15.0472529,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CzechiaMladaBoleslav,
					Places: []domain.Place{
						{
							Alias:           "cz-mlada-boleslav-clock-cafe",
							PreviousAliases: nil,
							City:            domain.CzechiaMladaBoleslav,
							Name:            "Clock Café",
							Address:         "Českobratrské nám. 57/3, 293 01 Mladá Boleslav, Česká republika",
							Type:            domain.Cafe,
							URL:             "https://clockcafe.cz/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/kavarnaclockcafe/",
							FacebookURL:     "https://www.facebook.com/kavarnaclockcafe/",
							GoogleMapsURL:   "https://www.google.com/maps/place/CLOCK+CAF%C3%89/@50.4140055,14.9048264,17z/data=!3m1!4b1!4m6!3m5!1s0x4709554d3f3e75eb:0x1793494cc33fae3e!8m2!3d50.4140055!4d14.9048264!16s%2Fg%2F11lj13k5pw?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ63U-P01VCUcRPq4_w0xJkxc",
							Location: domain.Location{
								Latitude:  50.4140055,
								Longitude: 14.9048264,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CzechiaOlomouc,
					Places: []domain.Place{
						{
							Alias:           "cz-olomouc-simple-dumpl",
							PreviousAliases: nil,
							City:            domain.CzechiaOlomouc,
							Name:            "Simple Dumpl",
							Address:         "Denisova 310/13, 779 00 Olomouc, Česká republika",
							Type:            domain.Bistro,
							URL:             "https://simpledumpl.com/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/simple.dumpl/",
							FacebookURL:     "https://www.facebook.com/p/Simple-Dumpl-100066411355254/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Simple+Dumpl/@49.5955804,17.2544667,17z/data=!4m16!1m9!3m8!1s0x47124fe273b4b8fb:0x4e02c79a37fee123!2sSimple+Dumpl!8m2!3d49.5955804!4d17.2544667!9m1!1b1!16s%2Fg%2F11kq7tc9lj!3m5!1s0x47124fe273b4b8fb:0x4e02c79a37fee123!8m2!3d49.5955804!4d17.2544667!16s%2Fg%2F11kq7tc9lj?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ-7i0c-JPEkcRI-H-N5rHAk4",
							Location: domain.Location{
								Latitude:  49.5955804,
								Longitude: 17.2544667,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CzechiaPardubice,
					Places: []domain.Place{
						{
							Alias:           "cz-pardubice-berehynia",
							PreviousAliases: nil,
							City:            domain.CzechiaPardubice,
							Name:            "Berehynia Ukrajinská kuchyně",
							Address:         "Náměstí Republiky 53, 530 02 Pardubice, Česká republika",
							Type:            domain.Restaurant,
							URL:             "https://bleriotpardubice.cz/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "",
							FacebookURL:     "https://www.facebook.com/bleriotpardubice/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Berehynia+Ukrajinsk%C3%A1+kuchyn%C4%9B/@50.0241904,15.7596832,17z/data=!4m16!1m9!3m8!1s0x470dcd0c277016f3:0x84d8e59e320c4a37!2sBerehynia+Ukrajinsk%C3%A1+kuchyn%C4%9B!8m2!3d50.0241904!4d15.7596832!9m1!1b1!16s%2Fg%2F11l5s392gk!3m5!1s0x470dcd0c277016f3:0x84d8e59e320c4a37!8m2!3d50.0241904!4d15.7596832!16s%2Fg%2F11l5s392gk?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ8xZwJwzNDUcRN0oMMp7l2IQ",
							Location: domain.Location{
								Latitude:  50.0241904,
								Longitude: 15.7596832,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CzechiaPraha,
					Places: []domain.Place{
						{
							Alias:           "cz-praha-bistro-panska",
							PreviousAliases: nil,
							City:            domain.CzechiaPraha,
							Name:            "Bistro Panská (Soloha)",
							Address:         "Panská 1, 110 00 Praha 1-Nové Město, Česká republika",
							Type:            domain.Bistro,
							URL:             "https://bistropanska.choiceqr.com/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/Bistro+Pansk%C3%A1/@50.0850006,14.4265641,17z/data=!3m1!4b1!4m6!3m5!1s0x470b95906896b343:0xea8dc47248e9e0a5!8m2!3d50.0850006!4d14.4265641!16s%2Fg%2F11tjs8tyth?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJQ7OWaJCVC0cRpeDpSHLEjeo",
							Location: domain.Location{
								Latitude:  50.0850006,
								Longitude: 14.4265641,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
						{
							Alias:           "cz-praha-bistro-soloha",
							PreviousAliases: nil,
							City:            domain.CzechiaPraha,
							Name:            "Bistro Soloha",
							Address:         "J. Masaryka 36, 120 00 Praha 2-Vinohrady, Česká republika",
							Type:            domain.Bistro,
							URL:             "https://soloha.uds.app/c",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/soloha_bistro/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/Bistro+Soloha/@50.07385,14.4314889,3334m/data=!3m1!1e3!4m10!1m2!2m1!1sbistro+soloha+prague!3m6!1s0x470b95acb17d668d:0xc4b603ddcf9f9cca!8m2!3d50.0718449!4d14.4395247!15sChRiaXN0cm8gc29sb2hhIHByYWd1ZVoWIhRiaXN0cm8gc29sb2hhIHByYWd1ZZIBBmJpc3Ryb5oBRENpOURRVWxSUVVOdlpFTm9kSGxqUmpsdlQyczBNMWx0TVhwVk0wNUtaREJ3TlZOSVZuaFZSRTVVVjFod1psZHRZeEFC4AEA-gEFCMIBEDo!16s%2Fg%2F11vzph9zm8?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJjWZ9sayVC0cRypyfz90DtsQ",
							Location: domain.Location{
								Latitude:  50.07385,
								Longitude: 14.4314889,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
						{
							Alias:           "cz-praha-dnister",
							PreviousAliases: nil,
							City:            domain.CzechiaPraha,
							Name:            "Dnister",
							Address:         "Na Moráni 6, 128 00 Praha 2-Nové Město, Česká republika",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/restauracednister?utm_source=qr",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/Dnister/@50.0732496,14.4159963,17z/data=!3m1!4b1!4m6!3m5!1s0x470b94f5d5d2b7d5:0x4eecebf9708c3056!8m2!3d50.0732496!4d14.4159963!16s%2Fg%2F11b6v4fk_x?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ1bfS1fWUC0cRVjCMcPnr7E4",
							Location: domain.Location{
								Latitude:  50.0732496,
								Longitude: 14.4159963,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
						{
							Alias:           "cz-praha-nashi",
							PreviousAliases: nil,
							City:            domain.CzechiaPraha,
							Name:            "NAШІ",
							Address:         "Křižíkova 160/71, 186 00 Praha 8-Karlín, Česká republika",
							Type:            domain.Restaurant,
							URL:             "https://nashi.cz/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/nashi_restaurace/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/NA%C5%A0I+restaurace/@50.095799,14.4468279,15.35z/data=!4m12!1m2!2m1!1z0J3QkNCo0IYgcmVzdGF1cmFudCBwcmFndWU!3m8!1s0x470b95002f0b29ad:0x67575eb65936dd92!8m2!3d50.0926188!4d14.4510904!9m1!1b1!15sChrQndCQ0KjQhiByZXN0YXVyYW50IHByYWd1ZVocIhrQvdCw0YjRliByZXN0YXVyYW50IHByYWd1ZZIBCnJlc3RhdXJhbnSaASNDaFpEU1VoTk1HOW5TMFZKUTBGblRVUkJNWFZ1YVZOQkVBReABAPoBBQiiARAo!16s%2Fg%2F11wp5cqfs7?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJrSkLLwCVC0cRkt02WbZeV2c",
							Location: domain.Location{
								Latitude:  50.095799,
								Longitude: 14.4468279,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
						{
							Alias:           "cz-praha-the-borsc",
							PreviousAliases: nil,
							City:            domain.CzechiaPraha,
							Name:            "The Boršč",
							Address:         "Dukelských Hrdinů 10, 170 00 Praha 7-Holešovice, Česká republika",
							Type:            domain.Restaurant,
							URL:             "https://theborsch.cz/uk",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/the___borsch/?hl=en",
							FacebookURL:     "https://www.facebook.com/TheBorschPrague/",
							GoogleMapsURL:   "https://www.google.com/maps/place/The+Bor%C5%A1%C4%8D/@50.098465,14.433446,3762m/data=!3m1!1e3!4m15!1m8!3m7!1s0x470b94c7babea689:0x57ccaab0ab46b29f!2zRHVrZWxza8O9Y2ggSHJkaW7FryAxMCwgMTcwIDAwIFByYWhhIDctSG9sZcWhb3ZpY2UsINCn0LXRhdC40Y8!3b1!8m2!3d50.0984655!4d14.4334462!16s%2Fg%2F11sjsfrbmr!3m5!1s0x470b952e39f771d1:0x372d3f7ba381c4f8!8m2!3d50.0984655!4d14.4334462!16s%2Fg%2F11x0g10p7t?hl=ru-RU&entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ0XH3OS6VC0cR-MSBo3s_LTc",
							Location: domain.Location{
								Latitude:  50.098465,
								Longitude: 14.433446,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CzechiaVranovNadDyji,
					Places: []domain.Place{
						{
							Alias:           "cz-vranov-nad-dyji-bud-laska",
							PreviousAliases: nil,
							City:            domain.CzechiaVranovNadDyji,
							Name:            "Buď Laska",
							Address:         "8. května 92, 671 03 Vranov nad Dyjí, Česká republika",
							Type:            domain.Restaurant,
							URL:             "https://www.budlaska.eu/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/budlaskavranov/",
							FacebookURL:     "https://www.facebook.com/budlaskavranov/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Bu%C4%8F+Laska/@48.8964509,15.8127007,17z/data=!4m16!1m9!3m8!1s0x4772adec56937295:0x8162cf21c6ae357!2sBu%C4%8F+Laska!8m2!3d48.8964509!4d15.8127007!9m1!1b1!16s%2Fg%2F11t27jyc5k!3m5!1s0x4772adec56937295:0x8162cf21c6ae357!8m2!3d48.8964509!4d15.8127007!16s%2Fg%2F11t27jyc5k?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJlXKTVuytckcRV-NqHPIsFgg",
							Location: domain.Location{
								Latitude:  48.8964509,
								Longitude: 15.8127007,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.CzechiaUstiNadLabem,
					Places: []domain.Place{
						{
							Alias:           "cz-usti-nad-labem-zlate-karpaty",
							PreviousAliases: nil,
							City:            domain.CzechiaUstiNadLabem,
							Name:            "Restaurace Zlaté Karpaty",
							Address:         "Hornická 2511/10a, 400 11 Ústí nad Labem-centrum, Česká republika",
							Type:            domain.Restaurant,
							URL:             "https://zlatekarpaty.cz/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/zlate.karpaty/",
							FacebookURL:     "https://www.facebook.com/p/Restaurace-Zlat%C3%A9-Karpaty-61574925617403/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Restaurace+Zlat%C3%A9+Karpaty/@50.6715865,14.029694,17z/data=!4m16!1m9!3m8!1s0x47099b64006de1f7:0xc88bd350532ba05c!2sRestaurace+Zlat%C3%A9+Karpaty!8m2!3d50.6715865!4d14.029694!9m1!1b1!16s%2Fg%2F11wqh3lj_c!3m5!1s0x47099b64006de1f7:0xc88bd350532ba05c!8m2!3d50.6715865!4d14.029694!16s%2Fg%2F11wqh3lj_c?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ9-FtAGSbCUcRXKArU1DTi8g",
							Location: domain.Location{
								Latitude:  50.6715865,
								Longitude: 14.029694,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-01"),
							PromotedUntil: nil,
						},
					},
				},
			},
		},
		{
			Country: domain.Germany,
			Cities: []domain.CityPlaceGroup{
				{
					City: domain.GermanyBerlin,
					Places: []domain.Place{
						{
							Alias:           "de-berlin-die-mit-den-kirschen",
							PreviousAliases: nil,
							City:            domain.GermanyBerlin,
							Name:            "Die mit den Kirschen",
							Address:         "Wielandstraße 38, 10629 Berlin, Германия",
							Type:            domain.Restaurant,
							URL:             "https://ukrainische-restaurant-in-berlin.de/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/die_mit_den_kirschen",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/Die+mit+den+Kirschen+-+ukrainische+moderne+K%C3%BCche/@52.5041102,13.3157947,892m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47a851a88f1fb819:0x978b135a20ab3c18!8m2!3d52.5041102!4d13.3157947!16s%2Fg%2F11srymlb23?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJGbgfj6hRqEcRGDyrIFoTi5c",
							Location: domain.Location{
								Latitude:  52.5041102,
								Longitude: 13.3157947,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
						{
							Alias:           "de-berlin-fayna-restaurant",
							PreviousAliases: nil,
							City:            domain.GermanyBerlin,
							Name:            "Fayna Restaurant",
							Address:         "Klopstockstraße 2, 10557 Berlin, Германия",
							Type:            domain.Restaurant,
							URL:             "https://www.fayna.rest/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/fayna_restaurant/",
							FacebookURL:     "https://www.facebook.com/p/Fayna-Restaurant-61559303705022/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Fayna+Restaurant/@52.5148307,13.3390653,892m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47a851f67e78d811:0x1ddc18c0016bfc3e!8m2!3d52.5148307!4d13.3390653!16s%2Fg%2F11wmn7hwxz?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJEdh4fvZRqEcRPvxrAcAY3B0",
							Location: domain.Location{
								Latitude:  52.5148307,
								Longitude: 13.3390653,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
						{
							Alias:           "de-berlin-odessa-mama",
							PreviousAliases: nil,
							City:            domain.GermanyBerlin,
							Name:            "Odessa Mama",
							Address:         "Innsbrucker Platz 3, 10827 Berlin-Bezirk Tempelhof-Schöneberg, Германия",
							Type:            domain.Restaurant,
							URL:             "https://odessamama.de/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/odessamamaberlin/",
							FacebookURL:     "https://www.facebook.com/odessamamaberlin",
							GoogleMapsURL:   "https://www.google.com/maps/place/Odessa+Mama/@52.4785357,13.3450057,17z/data=!3m1!4b1!4m6!3m5!1s0x47a84e6ec7b3be6b:0xa6a7c6c32cee7771!8m2!3d52.4785357!4d13.3450057!16s%2Fg%2F11f5r9pybr",
							GooglePlaceID:   "ChIJbb6zx25QqEcRcXfuLMPGp6Y",
							Location: domain.Location{
								Latitude:  52.4785357,
								Longitude: 13.3450057,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
						{
							Alias:           "de-berlin-guzulka",
							PreviousAliases: nil,
							City:            domain.GermanyBerlin,
							Name:            "Restaurant Guzulka",
							Address:         "Alt-Rudow 1, 12357 Berlin, Германия",
							Type:            domain.Restaurant,
							URL:             "https://guzulka.eatbu.com/?lang=de",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/restaurant_guzulka/",
							FacebookURL:     "https://www.facebook.com/RestaurantGuzulka/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Restaurant+Guzulka/@52.4220292,13.4889948,894m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47a8472f40cbf4f5:0x3e91bc17697254a9!8m2!3d52.4220292!4d13.4889948!16s%2Fg%2F11f7b_d66d?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ9fTLQC9HqEcRqVRyaRe8kT4",
							Location: domain.Location{
								Latitude:  52.4220292,
								Longitude: 13.4889948,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyBonn,
					Places: []domain.Place{
						{
							Alias:           "de-bonn-nowa-mowa",
							PreviousAliases: nil,
							City:            domain.GermanyBonn,
							Name:            "Nowa Mowa",
							Address:         "Paulstraße 5, 53111 Bonn, Германия",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/nowamowa.bonn/",
							FacebookURL:     "https://www.facebook.com/61572615720010/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Nowa+Mowa/@50.7402305,7.096146,928m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47bee113889eb355:0x334de087ae490393!8m2!3d50.7402305!4d7.096146!16s%2Fg%2F11wy17l98w?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJVbOeiBPhvkcRkwNJrofgTTM",
							Location: domain.Location{
								Latitude:  50.7402305,
								Longitude: 7.096146,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyBremen,
					Places: []domain.Place{
						{
							Alias:           "de-bremen-bab-maria",
							PreviousAliases: nil,
							City:            domain.GermanyBremen,
							Name:            "Bab' Maria (Oma Maria)",
							Address:         "Markthalle Acht, BAB’ MARIA (Oma Maria), Ukrainische Küche, Domshof 8-12, 28195 Bremen, Германия",
							Type:            domain.Bistro,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/babmaria_ukrainian_cuisine/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/BAB'+MARIA+(OMA+MARIA).+Ein+Teller+voller+Heimat.+Die+erste+traditionelle+ukrainische+K%C3%BCche+in+Bremen.+Seit+2019./@53.0758402,8.8102444,881m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47b12998c427e8a5:0xffc07f31e216b747!8m2!3d53.0758402!4d8.8102444!16s%2Fg%2F11j1109wdd?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJpegnxJgpsUcRR7cW4jF_wP8",
							Location: domain.Location{
								Latitude:  53.0758402,
								Longitude: 8.8102444,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
						{
							Alias:           "de-bremen-dnipro-restaurant",
							PreviousAliases: nil,
							City:            domain.GermanyBremen,
							Name:            "Dnipro Restaurant",
							Address:         "Fedelhören 36, 28203 Bremen, Германия",
							Type:            domain.Restaurant,
							URL:             "https://www.dnipro-restaurant.com/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/dnipro_restaurant/",
							FacebookURL:     "https://www.facebook.com/p/Dnipro-Bremen-100087781073168/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Dnipro+Restaurant/@53.0779153,8.819774,881m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47b12986fc0af7a5:0xe7a8223e92b40c6!8m2!3d53.0779153!4d8.819774!16s%2Fg%2F11jz42lwlg?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJpfcK_IYpsUcRxkAr6SOCeg4",
							Location: domain.Location{
								Latitude:  53.0779153,
								Longitude: 8.819774,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyDatteln,
					Places: []domain.Place{
						{
							Alias:           "de-datteln-fayno",
							PreviousAliases: nil,
							City:            domain.GermanyDatteln,
							Name:            "Ukrainisches Restaurant FAYNO",
							Address:         "Castroper Str. 88, 45711 Datteln, Германия",
							Type:            domain.Restaurant,
							URL:             "https://fayno-restaurant.eatbu.com/?lang=de",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/fayno_restaurant",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/Ukrainisches+Restaurant+FAYNO/@51.6453414,7.3375646,910m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47b903888d631ecb:0x6b92bf3a9393d777!8m2!3d51.6453414!4d7.3375646!16s%2Fg%2F11x7ktf7r7?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJyx5jjYgDuUcRd9eTkzq_kms",
							Location: domain.Location{
								Latitude:  51.6453414,
								Longitude: 7.3375646,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyDortmund,
					Places: []domain.Place{
						{
							Alias:           "de-dortmund-babuschkas-kitchen",
							PreviousAliases: nil,
							City:            domain.GermanyDortmund,
							Name:            "Babuschkas Kitchen",
							Address:         "Kreuzstraße 69, 44139 Dortmund, Германия",
							Type:            domain.Restaurant,
							URL:             "https://babuschkas.kitchen/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/babuschkas.kitchen/",
							FacebookURL:     "https://www.facebook.com/Babuschkas/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Babuschkas+Kitchen/@51.5027155,7.4532601,576m/data=!3m1!1e3!4m16!1m9!3m8!1s0x47b919b86860a877:0x9304923ae9db47e2!2sBabuschkas+Kitchen!8m2!3d51.5027155!4d7.4532601!9m1!1b1!16s%2Fg%2F11m450kl2f!3m5!1s0x47b919b86860a877:0x9304923ae9db47e2!8m2!3d51.5027155!4d7.4532601!16s%2Fg%2F11m450kl2f?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJd6hgaLgZuUcR4kfb6TqSBJM",
							Location: domain.Location{
								Latitude:  51.5027155,
								Longitude: 7.4532601,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyDresden,
					Places: []domain.Place{
						{
							Alias:           "de-dresden-restaurant-matius",
							PreviousAliases: nil,
							City:            domain.GermanyDresden,
							Name:            "Restaurant MATIUS",
							Address:         "Nieritzstraße 9, 01097 Dresden, Германия",
							Type:            domain.Restaurant,
							URL:             "https://matius.de/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/restaurant_matius/",
							FacebookURL:     "https://www.facebook.com/profile.php?id=61569274162273",
							GoogleMapsURL:   "https://www.google.com/maps/place/Restaurant+MATIUS/@51.0622971,13.7411175,581m/data=!3m2!1e3!4b1!4m6!3m5!1s0x4709cf9325a2eb93:0xc936213374cda4e9!8m2!3d51.0622971!4d13.7411175!16s%2Fg%2F11wq4qp61h?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJk-uiJZPPCUcR6aTNdDMhNsk",
							Location: domain.Location{
								Latitude:  51.0622971,
								Longitude: 13.7411175,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyDusseldorf,
					Places: []domain.Place{
						{
							Alias:           "de-dusseldorf-schu-schu",
							PreviousAliases: nil,
							City:            domain.GermanyDusseldorf,
							Name:            "Schu Schu Restaurant",
							Address:         "Eisenstraße 41, 40227 Düsseldorf, Германия",
							Type:            domain.Restaurant,
							URL:             "https://schuschu-restaurant.de/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/schuschuduesseldorf/",
							FacebookURL:     "https://www.facebook.com/schuschurestaurant",
							GoogleMapsURL:   "https://www.google.com/maps/place/Schu+Schu+Restaurant/@51.2170654,6.7961529,918m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47b8ca341486d2dd:0x39254dda4c913ba!8m2!3d51.2170654!4d6.7961529!16s%2Fg%2F1tfpyy7r?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ3dKGFDTKuEcRuhPJpN1UkgM",
							Location: domain.Location{
								Latitude:  51.2170654,
								Longitude: 6.7961529,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyFrankfurtAmMain,
					Places: []domain.Place{
						{
							Alias:           "de-frankfurt-mavka",
							PreviousAliases: nil,
							City:            domain.GermanyFrankfurtAmMain,
							Name:            "Mavka",
							Address:         "Wasgaustraße 19A, 65929 Frankfurt am Main, Германия",
							Type:            domain.Restaurant,
							URL:             "https://www.mavka-ua.com/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/restaurantmavka_frankfurt/",
							FacebookURL:     "https://www.facebook.com/p/Restaurant-Mavka-61566034138857/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Mavka/@50.10992,8.5362211,940m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47bda12de0f91d2d:0x836467242cee390!8m2!3d50.10992!4d8.5362211!16s%2Fg%2F11w874pml5?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJLR354C2hvUcRkOPOQnJGNgg",
							Location: domain.Location{
								Latitude:  50.10992,
								Longitude: 8.5362211,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyHannover,
					Places: []domain.Place{
						{
							Alias:           "de-hannover-smak",
							PreviousAliases: nil,
							City:            domain.GermanyHannover,
							Name:            "SMAK Familienrestaurant",
							Address:         "Groß-Buchholzer Straße 9, 30655 Hannover, Германия",
							Type:            domain.Restaurant,
							URL:             "https://smak-restaurant.de/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/smak1581/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/SMAK+Familienrestaurant/@52.3986605,9.8019864,895m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47b00d4328096f39:0x9521d5a1aa20d37c!8m2!3d52.3986605!4d9.8019864!16s%2Fg%2F11s3xnrpc4?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJOW8JKEMNsEcRfNMgqqHVIZU",
							Location: domain.Location{
								Latitude:  52.3986605,
								Longitude: 9.8019864,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyKarlsruhe,
					Places: []domain.Place{
						{
							Alias:           "de-karlsruhe-restaurant-odessa",
							PreviousAliases: nil,
							City:            domain.GermanyKarlsruhe,
							Name:            "Restaurant Odessa",
							Address:         "Otto-Wels-Straße 35, 76189 Karlsruhe, Германия",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/odessakarlsruhe/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/Restaurant+Odessa/@48.9856114,8.3632261,962m/data=!3m2!1e3!4b1!4m6!3m5!1s0x4797071bc529eb51:0x4c05a66f66086bb4!8m2!3d48.9856114!4d8.3632261!16s%2Fg%2F11vpqxnvpf?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJUespxRsHl0cRtGsIZm-mBUw",
							Location: domain.Location{
								Latitude:  48.9856114,
								Longitude: 8.3632261,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyKoln,
					Places: []domain.Place{
						{
							Alias:           "de-koln-restaurant-odessa",
							PreviousAliases: nil,
							City:            domain.GermanyKoln,
							Name:            "Restaurant Odessa",
							Address:         "Im Ferkulum 32, 50678 Köln, Германия",
							Type:            domain.Restaurant,
							URL:             "https://restaurantodessa.de/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/restaurant_odessa_koeln/",
							FacebookURL:     "https://www.facebook.com/p/Restaurant-ODESSA-100063583780984/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Odessa/@50.9229718,6.9601044,924m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47bf24492c66d751:0xd888ff2164ddc450!8m2!3d50.9229718!4d6.9601044!16s%2Fg%2F1tgkgf4c?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJUddmLEkkv0cRUMTdZCH_iNg",
							Location: domain.Location{
								Latitude:  50.9229718,
								Longitude: 6.9601044,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyMunchen,
					Places: []domain.Place{
						{
							Alias:           "de-munchen-ruta-bistro",
							PreviousAliases: nil,
							City:            domain.GermanyMunchen,
							Name:            "Ruta Munich",
							Address:         "Tulbeckstraße 9, 80339 München, Германия",
							Type:            domain.Bistro,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/ruta.munich/",
							FacebookURL:     "https://www.facebook.com/ruta.munich/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Ruta+Munich/@48.1367196,11.5428612,978m/data=!3m1!1e3!4m16!1m9!3m8!1s0x479dd9a05aba9543:0x1e5ff9177f216a5!2sRuta+Munich!8m2!3d48.1367196!4d11.5428612!9m1!1b1!16s%2Fg%2F11wqz11v1d!3m5!1s0x479dd9a05aba9543:0x1e5ff9177f216a5!8m2!3d48.1367196!4d11.5428612!16s%2Fg%2F11wqz11v1d?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJQ5W6WqDZnUcRpRbyd5H_5QE",
							Location: domain.Location{
								Latitude:  48.1367196,
								Longitude: 11.5428612,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyNurnberg,
					Places: []domain.Place{
						{
							Alias:           "de-nurnberg-dobro",
							PreviousAliases: nil,
							City:            domain.GermanyNurnberg,
							Name:            "DOBRO",
							Address:         "Morsestraße 9, 90459 Nürnberg, Deutschland",
							Type:            domain.Restaurant,
							URL:             "https://dobro.eatbu.com/?lang=de",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/dobronbg",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/DOBRO/@49.432235,11.0826262,954m/data=!3m2!1e3!4b1!4m6!3m5!1s0x479f576ccdd3f4df:0x423eb45de0cdb857!8m2!3d49.432235!4d11.0826262!16s%2Fg%2F11f2ch9nh0?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ3_TTzWxXn0cRV7jN4F20PkI",
							Location: domain.Location{
								Latitude:  49.432235,
								Longitude: 11.0826262,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
						{
							Alias:           "de-nurnberg-troianda",
							PreviousAliases: nil,
							City:            domain.GermanyNurnberg,
							Name:            "Ресторан ТРОЯНДА",
							Address:         "Marthweg 200, 90455 Nürnberg, Германия",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/trojanda.nuernberg/?hl=de/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/%D0%A0%D0%B5%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BD+%D0%A2%D0%A0%D0%9E%D0%AF%D0%9D%D0%94%D0%90/@49.3917435,11.0834419,954m/data=!3m1!1e3!4m16!1m9!3m8!1s0x479f511c0a060cd5:0x77e8d80b8435a4cd!2z0KDQtdGB0YLQvtGA0LDQvSDQotCg0J7Qr9Cd0JTQkA!8m2!3d49.391844!4d11.0832746!9m1!1b1!16s%2Fg%2F11vb6gm2n4!3m5!1s0x479f511c0a060cd5:0x77e8d80b8435a4cd!8m2!3d49.391844!4d11.0832746!16s%2Fg%2F11vb6gm2n4?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ1QwGChxRn0cRzaQ1hAvY6Hc",
							Location: domain.Location{
								Latitude:  49.3917435,
								Longitude: 11.0834419,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyPullachImIsartal,
					Places: []domain.Place{
						{
							Alias:           "de-pullach-druzi",
							PreviousAliases: nil,
							City:            domain.GermanyPullachImIsartal,
							Name:            "Druzi Bayrisch-Ukrainisches Restaurant",
							Address:         "Hans-Keis-Straße 59, 82049 Pullach im Isartal, Германия",
							Type:            domain.Restaurant,
							URL:             "https://druzi-pullach.de/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/druzi_restaurant_pullach/",
							FacebookURL:     "https://www.facebook.com/DruziPullach/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Druzi+Bayrisch-Ukrainisches+Restaurant/@48.0648169,11.5250773,980m/data=!3m2!1e3!4b1!4m6!3m5!1s0x479ddf000470ea83:0x2d5df30514ab62da!8m2!3d48.0648169!4d11.5250773!16s%2Fg%2F11y78_z_2j?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJg-pwBADfnUcR2mKrFAXzXS0",
							Location: domain.Location{
								Latitude:  48.0648169,
								Longitude: 11.5250773,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyRostock,
					Places: []domain.Place{
						{
							Alias:           "de-rostock-malvy",
							PreviousAliases: nil,
							City:            domain.GermanyRostock,
							Name:            "Malvy",
							Address:         "Doberaner Str. 147, 18057 Rostock, Германия",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/restaurant_malvy_rostock/",
							FacebookURL:     "https://www.facebook.com/61579783929250/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Malvy/@54.0889384,12.1218255,860m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47ac57002fd84aa5:0x83bd29d6935e2d26!8m2!3d54.0889384!4d12.1218255!16s%2Fg%2F11xtn0ws9y?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJpUrYLwBXrEcRJi1ek9YpvYM",
							Location: domain.Location{
								Latitude:  54.0889384,
								Longitude: 12.1218255,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyStrubbel,
					Places: []domain.Place{
						{
							Alias:           "de-strubbel-hutorok",
							PreviousAliases: nil,
							City:            domain.GermanyStrubbel,
							Name:            "Ukrainisches Restaurant Hutorok",
							Address:         "Dorfstraße 36, 25792 Strübbel, Германия",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/hutorok_de/",
							FacebookURL:     "https://www.facebook.com/hutorok.de/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Ukrainisches+Restaurant+Hutorok/@54.263702,8.968647,856m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47b477dec7758343:0xeaa1faf4d3edee34!8m2!3d54.263702!4d8.968647!16s%2Fg%2F11tmktzn0t?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJQ4N1x953tEcRNO7t0_T6oeo",
							Location: domain.Location{
								Latitude:  54.263702,
								Longitude: 8.968647,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.GermanyStuttgart,
					Places: []domain.Place{
						{
							Alias:           "de-stuttgart-topfle",
							PreviousAliases: nil,
							City:            domain.GermanyStuttgart,
							Name:            "Ukrainisches Restaurant Töpfle",
							Address:         "Bopserstraße 10, 70180 Stuttgart, Германия",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/toepfle.st",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/Ukrainisches+Restaurant+T%C3%B6pfle/@48.7698764,9.1793819,966m/data=!3m1!1e3!4m8!3m7!1s0x4799db3065d827cd:0x7961f7a8cbc96149!8m2!3d48.7698764!4d9.1793819!9m1!1b1!16s%2Fg%2F11yg5sx9cd?entry=ttu&g_ep=EgoyMDI2MDYyNC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJzSfYZTDbmUcRSWHJy6j3YXk",
							Location: domain.Location{
								Latitude:  48.7698764,
								Longitude: 9.1793819,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-25"),
							PromotedUntil: nil,
						},
					},
				},
			},
		},
		{
			Country: domain.Spain,
			Cities: []domain.CityPlaceGroup{
				{
					City: domain.SpainAlicante,
					Places: []domain.Place{
						{
							Alias:           "es-alicante-xata",
							PreviousAliases: nil,
							City:            domain.SpainAlicante,
							Name:            "Restaurante Xata",
							Address:         "Av. Artista Remigio Soler López, 9, 03540 Alicante, España",
							Type:            domain.Restaurant,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/restaurante.xata/",
							FacebookURL:     "https://www.facebook.com/Restaurante.Xata/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Xata/@38.3835876,-0.4145066,1149m/data=!3m2!1e3!4b1!4m6!3m5!1s0xd6239000d4f9f37:0x2c883e675f07e655!8m2!3d38.3835876!4d-0.4145066!16s%2Fg%2F11vywkr52c?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJN59PDQA5Yg0RVeYHX2c-iCw",
							Location: domain.Location{
								Latitude:  38.3835876,
								Longitude: -0.4145066,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-30"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.SpainBarcelona,
					Places: []domain.Place{
						{
							Alias:           "es-barcelona-korchma-rodyna",
							PreviousAliases: nil,
							City:            domain.SpainBarcelona,
							Name:            "Korchma Rodyna",
							Address:         "C/ de Muntaner, 443-445, Sarrià-Sant Gervasi, 08021 Barcelona, España",
							Type:            domain.Restaurant,
							URL:             "https://www.rodyna.es/uk",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/korchma.rodyna/",
							FacebookURL:     "https://www.facebook.com/korchma.rodyna/",
							GoogleMapsURL:   "https://www.google.com/maps/place/KORCHMA+RODYNA/@41.4011039,2.1399797,1100m/data=!3m2!1e3!4b1!4m6!3m5!1s0x12a4a3f9b2c75bef:0xa785d5380475bd6d!8m2!3d41.4011039!4d2.1399797!16s%2Fg%2F11k3d6qw41?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ71vHsvmjpBIRbb11BDjVhac",
							Location: domain.Location{
								Latitude:  41.4011039,
								Longitude: 2.1399797,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-30"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.SpainBenalmadena,
					Places: []domain.Place{
						{
							Alias:           "es-benalmadena-prosvita",
							PreviousAliases: nil,
							City:            domain.SpainBenalmadena,
							Name:            "Restaurante Prosvita",
							Address:         "Av. Manuel Mena Palma, 11, 29630 Benalmádena, Málaga, España",
							Type:            domain.Restaurant,
							URL:             "https://prosvita.es/uk",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/restaurante.prosvita/",
							FacebookURL:     "https://www.facebook.com/prosvit70/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Restaurante+Prosvita/@36.5889849,-4.5351053,1177m/data=!3m2!1e3!4b1!4m6!3m5!1s0xd72fdad0e633e6b:0x6b0cfae887fa7438!8m2!3d36.5889849!4d-4.5351053!16s%2Fg%2F11h58zwj06?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJaz5jDq39cg0ROHT6h-j6DGs",
							Location: domain.Location{
								Latitude:  36.5889849,
								Longitude: -4.5351053,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-30"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.SpainCurtis,
					Places: []domain.Place{
						{
							Alias:           "es-curtis-pasteleria-el-mundo",
							PreviousAliases: nil,
							City:            domain.SpainCurtis,
							Name:            "Pastelería El Mundo",
							Address:         "Av. Emilio Martínez Sánchez, 2, 15310 Curtis, A Coruña, España",
							Type:            domain.Bakery,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/elmundo_2025/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/pasteler%C3%ADa+El+Mundo/@43.1254223,-8.1455759,1070m/data=!3m2!1e3!4b1!4m6!3m5!1s0xd2e41b4a9bfee8f:0xe90282a9a38b3a88!8m2!3d43.1254223!4d-8.1455759!16s%2Fg%2F11xl3vymq3?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJj-6_qbRBLg0RiDqLo6mCAuk",
							Location: domain.Location{
								Latitude:  43.1254223,
								Longitude: -8.1455759,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-30"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.SpainMadrid,
					Places: []domain.Place{
						{
							Alias:           "es-madrid-kavovar",
							PreviousAliases: nil,
							City:            domain.SpainMadrid,
							Name:            "Kavovar Madrid",
							Address:         "Pl. Luca de Tena, 11, Arganzuela, 28045 Madrid, España",
							Type:            domain.Cafe,
							URL:             "",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/kavovar.madrid/",
							FacebookURL:     "",
							GoogleMapsURL:   "https://www.google.com/maps/place/KAVOVAR/@40.4017113,-3.6945119,1117m/data=!3m2!1e3!4b1!4m6!3m5!1s0xd4227003b8b4569:0x135c9036b1d88611!8m2!3d40.4017113!4d-3.6945119!16s%2Fg%2F11y6lplbsh?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJaUWLOwAnQg0REYbYsTaQXBM",
							Location: domain.Location{
								Latitude:  40.4017113,
								Longitude: -3.6945119,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-30"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.SpainSantFeliuDeLlobregat,
					Places: []domain.Place{
						{
							Alias:           "es-sant-feliu-de-llobregat-comida-ucraniana",
							PreviousAliases: nil,
							City:            domain.SpainSantFeliuDeLlobregat,
							Name:            "Comida Ucraniana",
							Address:         "Carrer Francesc Macià, 38, 08980 Sant Feliu de Llobregat, Barcelona, España",
							Type:            domain.Restaurant,
							URL:             "https://www.comidaucraniana.es/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/comidaukranianasf/",
							FacebookURL:     "https://www.facebook.com/p/Comidaucranianasf-100083355392057/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Comida+Ucraniana/@41.3843386,2.0477407,1100m/data=!3m2!1e3!4b1!4m6!3m5!1s0x12a49b80a7b85d19:0x21329deaf7897426!8m2!3d41.3843346!4d2.0503156!16s%2Fg%2F11rpttglyn?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJGV24p4CbpBIRJnSJ9-qdMiE",
							Location: domain.Location{
								Latitude:  41.3843386,
								Longitude: 2.0477407,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-30"),
							PromotedUntil: nil,
						},
					},
				},
				{
					City: domain.SpainValencia,
					Places: []domain.Place{
						{
							Alias:           "es-valencia-casa-ucraniana",
							PreviousAliases: nil,
							City:            domain.SpainValencia,
							Name:            "CASA UCRANIANA Restaurante",
							Address:         "Carrer de Padilla, 5, Ciutat Vella, 46001 Valencia, España",
							Type:            domain.Restaurant,
							URL:             "https://casa-ucraniana.es/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/casa.ucraniana.restaurante/",
							FacebookURL:     "https://www.facebook.com/CasaUcranianaRestaurante/",
							GoogleMapsURL:   "https://www.google.com/maps/place/CASA+UCRANIANA+Restaurante/@39.4699026,-0.3792018,1132m/data=!3m2!1e3!4b1!4m6!3m5!1s0xd604f4bfbc2cfab:0x165c5fdd6c328281!8m2!3d39.4699026!4d-0.3792018!16s%2Fg%2F11hbn69jwh?entry=ttu&g_ep=EgoyMDI2MDYyOC4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJq8_C-0tPYA0RgYIybN1fXBY",
							Location: domain.Location{
								Latitude:  39.4699026,
								Longitude: -0.3792018,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-06-30"),
							PromotedUntil: nil,
						},
					},
				},
			},
		},
		{
			Country: domain.Hungary,
			Cities: []domain.CityPlaceGroup{
				{
					City: domain.HungaryBudapest,
					Places: []domain.Place{
						{
							Alias:           "hu-budapest-mischenko-kitchen",
							PreviousAliases: nil,
							City:            domain.HungaryBudapest,
							Name:            "Mischenko Kitchen",
							Address:         "Budapest, Tompa u. 17/b, 1094 Magyarország",
							Type:            domain.Restaurant,
							URL:             "https://mischenko-kitchen.choiceqr.com/uk/section:menu",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/mischenko_kitchen/",
							FacebookURL:     "https://www.facebook.com/mischenko_kitchen-100091421747049/?locale=ru_RU",
							GoogleMapsURL:   "https://www.google.com/maps/place/Mischenko+kitchen/@47.4818939,19.0717913,17z/data=!3m1!4b1!4m6!3m5!1s0x4741dd4b01b85369:0x74e5987722807743!8m2!3d47.4818939!4d19.0717913!16s%2Fg%2F11txrtg529?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJaVO4AUvdQUcRQ3eAIneY5XQ",
							Location: domain.Location{
								Latitude:  47.4818939,
								Longitude: 19.0717913,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
						{
							Alias:           "hu-budapest-svoi-bisztro",
							PreviousAliases: nil,
							City:            domain.HungaryBudapest,
							Name:            "SVOI bisztró",
							Address:         "Budapest, Nádor u. 34, 1051 Magyarország",
							Type:            domain.Bistro,
							URL:             "https://svoi-bisztro.com/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "https://www.instagram.com/svoi.bisztro/",
							FacebookURL:     "https://www.facebook.com/people/SVOI-bisztr%C3%B3/61568756008040/",
							GoogleMapsURL:   "https://www.google.com/maps/place/SVOI+bisztr%C3%B3/@47.5049181,19.0479651,17z/data=!4m16!1m9!3m8!1s0x4741ddeae1f7e7e1:0x53f6c46c8560cde2!2sSVOI+bisztr%C3%B3!8m2!3d47.5049181!4d19.0479651!9m1!1b1!16s%2Fg%2F11wn71bnr5!3m5!1s0x4741ddeae1f7e7e1:0x53f6c46c8560cde2!8m2!3d47.5049181!4d19.0479651!16s%2Fg%2F11wn71bnr5?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ4ef34erdQUcR4s1ghWzE9lM",
							Location: domain.Location{
								Latitude:  47.5049181,
								Longitude: 19.0479651,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
						{
							Alias:           "hu-budapest-ukran-udvar-rady",
							PreviousAliases: nil,
							City:            domain.HungaryBudapest,
							Name:            "Ukrán Udvar Étterem",
							Address:         "Budapest, Ráday u. 17, 1092 Magyarország",
							Type:            domain.Restaurant,
							URL:             "https://ukranudvar.hu//",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "",
							FacebookURL:     "https://www.facebook.com/UkranUdvar",
							GoogleMapsURL:   "https://www.google.com/maps/place/Ukr%C3%A1n+Udvar+%C3%89tterem/@47.4865807,19.0636159,17z/data=!3m1!4b1!4m6!3m5!1s0x4741dd7c340547d9:0xa76e64525e99d45f!8m2!3d47.4865807!4d19.0636159!16s%2Fg%2F11g0599g2b?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJ2UcFNHzdQUcRX9SZXlJkbqc",
							Location: domain.Location{
								Latitude:  47.4865807,
								Longitude: 19.0636159,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
						{
							Alias:           "hu-budapest-ukran-udvar-karoly",
							PreviousAliases: nil,
							City:            domain.HungaryBudapest,
							Name:            "Ukrán Udvar Étterem Károly körút",
							Address:         "Budapest, Károly krt. 26, 1052 Magyarország",
							Type:            domain.Restaurant,
							URL:             "https://ukranudvar.hu/",
							MenuURL:         "",
							PhotoURL:        "",
							InstagramURL:    "",
							FacebookURL:     "https://www.facebook.com/UkranUdvar/",
							GoogleMapsURL:   "https://www.google.com/maps/place/Ukr%C3%A1n+Udvar+%C3%89tterem+K%C3%A1roly+k%C3%B6r%C3%BAt/@47.4960949,19.0575159,14z/data=!4m10!1m2!2m1!1zVWtyw6FuIFVkdmFyIMOJdHRlcmVtIEvDoXJvbHkga8O2csO6dCBidWRhcGVzdA!3m6!1s0x4741dd319cead937:0x179cfa05562fdfd0!8m2!3d47.4960949!4d19.0575159!15sCi5Va3LDoW4gVWR2YXIgw4l0dGVyZW0gS8Ohcm9seSBrw7Zyw7p0IGJ1ZGFwZXN0WjAiLnVrcsOhbiB1ZHZhciDDqXR0ZXJlbSBrw6Fyb2x5IGvDtnLDunQgYnVkYXBlc3SSARR1a3JhaW5pYW5fcmVzdGF1cmFudJoBRENpOURRVWxSUVVOdlpFTm9kSGxqUmpsdlQydE9UMlJIVGsxaVdFSkpUVWRGZVZnd2JHOWhWbFY0VFROd05FOUdSUkFC4AEA-gEFCJoBECs!16s%2Fg%2F11tnd1t77z?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
							GooglePlaceID:   "ChIJN9nqnDHdQUcR0N8vVgX6nBc",
							Location: domain.Location{
								Latitude:  47.4960949,
								Longitude: 19.0575159,
							},
							FoundingYear:  0,
							Description:   "",
							Dishes:        nil,
							BorschPrice:   "",
							LargePortions: false,
							HasDelivery:   false,
							DonatesToZSU:  nil,
							Articles:      nil,
							YoutubeVideos: nil,
							AddedAt:       mustDate("2026-07-02"),
							PromotedUntil: nil,
						},
					},
				},
			},
		},
		{
			Country: domain.Poland,
			Cities:  []domain.CityPlaceGroup{
				// ...
			},
		},
		{
			Country: domain.Portugal,
			Cities:  []domain.CityPlaceGroup{
				// ...
			},
		},
		{
			Country: domain.Romania,
			Cities:  []domain.CityPlaceGroup{
				// ...
			},
		},
		{
			Country: domain.Slovakia,
			Cities:  []domain.CityPlaceGroup{
				// ...
			},
		},
		{
			Country: domain.Turkiye,
			Cities:  []domain.CityPlaceGroup{
				// ...
			},
		},
	}
}

// PlacesOld завантажує сирі дані (1.2), мапить кожен запис у domain.Place (1.3)
// і повертає їх згрупованими по країнах і містах (internal_docs/task_01.md, 1.4).
// Помилки завантаження/мапінгу — це збій даних на етапі білда, тому панікуємо
// (як mustDate), а не повертаємо error: сигнатура PlacesOld() лишається старою.
func PlacesOld() ([]domain.CountryPlaceGroup, error) {
	dtos, err := loadPlaceDTOs()
	if err != nil {
		return nil, fmt.Errorf("db: завантаження даних: %w", err)
	}
	places := make([]domain.Place, 0, len(dtos))
	for _, dto := range dtos {
		place, err := dtoToPlace(dto)
		if err != nil {
			return nil, fmt.Errorf("db: мапінг заведення: %w", err)
		}
		places = append(places, place)
	}
	return groupPlaces(places), nil
}

// cityKey — унікальний ключ міста в межах усього набору: alias міста сам по
// собі не унікальний між країнами (напр. однаковий alias у двох країнах).
type cityKey struct {
	countryAlias string
	cityAlias    string
}

// groupPlaces групує плаский список заведень у []domain.CountryPlaceGroup:
// країна -> місто -> заклади. У межах міста дедуплікує alias і сортує заклади
// за назвою; країни й міста сортуються за alias — усе для відтворюваності
// порядку між білдами.
func groupPlaces(places []domain.Place) []domain.CountryPlaceGroup {
	countries := map[string]domain.Country{}
	cities := map[cityKey]domain.City{}
	byCity := map[cityKey][]domain.Place{}
	cityAliasesByCountry := map[string]map[string]bool{}

	for _, p := range places {
		key := cityKey{countryAlias: p.City.Country.Alias, cityAlias: p.City.Alias}

		countries[key.countryAlias] = p.City.Country
		cities[key] = p.City
		byCity[key] = append(byCity[key], p)

		if cityAliasesByCountry[key.countryAlias] == nil {
			cityAliasesByCountry[key.countryAlias] = map[string]bool{}
		}
		cityAliasesByCountry[key.countryAlias][key.cityAlias] = true
	}

	countryAliases := make([]string, 0, len(countries))
	for alias := range countries {
		countryAliases = append(countryAliases, alias)
	}
	sort.Strings(countryAliases)

	groups := make([]domain.CountryPlaceGroup, 0, len(countryAliases))
	for _, countryAlias := range countryAliases {
		cityAliases := make([]string, 0, len(cityAliasesByCountry[countryAlias]))
		for alias := range cityAliasesByCountry[countryAlias] {
			cityAliases = append(cityAliases, alias)
		}
		sort.Strings(cityAliases)

		cityGroups := make([]domain.CityPlaceGroup, 0, len(cityAliases))
		for _, cityAlias := range cityAliases {
			key := cityKey{countryAlias: countryAlias, cityAlias: cityAlias}
			cityPlaces := byCity[key]

			sort.SliceStable(cityPlaces, func(i, j int) bool {
				if cityPlaces[i].Name != cityPlaces[j].Name {
					return cityPlaces[i].Name < cityPlaces[j].Name
				}
				if cityPlaces[i].Alias != cityPlaces[j].Alias {
					return cityPlaces[i].Alias < cityPlaces[j].Alias
				}
				// Фінальний тай-брейк по GooglePlaceID (непустий і унікальний
				// для всіх заведень): порядок при повному збігу Name/Alias не
				// має залежати від позиції запису у вхідному файлі, інакше
				// призначення суфікса -2 "пливе" між білдами (internal_docs/task_01.md, 1.4.1).
				return cityPlaces[i].GooglePlaceID < cityPlaces[j].GooglePlaceID
			})
			dedupeAliases(cityPlaces)

			cityGroups = append(cityGroups, domain.CityPlaceGroup{
				City:   cities[key],
				Places: cityPlaces,
			})
		}

		groups = append(groups, domain.CountryPlaceGroup{
			Country: countries[countryAlias],
			Cities:  cityGroups,
		})
	}

	return groups
}

// dedupeAliases додає детермінований суфікс -2, -3, ... до повторюваних
// Place.Alias у межах уже відсортованого зрізу заведень одного міста.
// `used` враховує і вихідні, і вже згенеровані alias, тому кандидат base-N
// перевіряється на зайнятість перед призначенням — інакше можна випадково
// зіткнутися з "натуральним" alias виду base-2, що вже є серед заведень
// (internal_docs/task_01.md, 1.4.1).
func dedupeAliases(places []domain.Place) {
	used := make(map[string]bool, len(places))
	for _, p := range places {
		used[p.Alias] = true
	}

	seen := map[string]int{}
	for i := range places {
		base := places[i].Alias
		seen[base]++
		if seen[base] == 1 {
			continue // перше входження лишається без суфікса
		}

		n := seen[base]
		candidate := fmt.Sprintf("%s-%d", base, n)
		for used[candidate] {
			n++
			candidate = fmt.Sprintf("%s-%d", base, n)
		}

		places[i].Alias = candidate
		used[candidate] = true
		seen[base] = n
	}
}
